apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: http://acme-v02.api.letsencrypt.org/directory
    email: samvith.cs@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}

